version: "3"
services:
  db_warung_pintar:
    image: mysql:8.0
    container_name: db_warung_pintar
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: secret
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
volumes:
  mysql-data:
