name: ci-test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      mysql:
        # Docker Hub image
        image: mysql:8.0
        # Provide the user and  password for MySQL
        env:
          MYSQL_USER: secret
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: user_tests
        ports:
          # Maps tcp port 5432 on service container to the host
          - 3306:3306
        # Set health checks to wait until postgres has started
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      # Install go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
        id: go

      # Checkout code
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      # Run test with code on file Makefile
      - name: Test
        run: make test
